xp_cost: 2
messages:
  no_item: "§cYou must hold an item in your hand!"
  not_enough_xp: "§cYou do not have enough XP!"
  repaired: "§aYour item has been repaired!"
  renamed: "§aYour item has been renamed!"
