repair_xp_cost: 50
rename_xp_cost: 50
messages:
  no_item: "&cYou are not holding any item!"
  not_enough_xp: "&cYou do not have enough XP to do this!"
  repair_success: "&aYour item has been repaired!"
  rename_success: "&aYour item has been renamed!"
  enter_name: "&eEnter the new name for your item:"
rename_placeholder: "&eCustom Name"
