repair:
  xp-cost: 2
  success-message: "§aYour item has been repaired!"
  not-enough-xp: "§cYou do not have enough XP to repair this item!"

rename:
  xp-cost: 2
  success-message: "§aYour item has been renamed!"
  not-enough-xp: "§cYou do not have enough XP to rename this item!"
  default-name: "§fYour Item"
